# Your Discord bot's bot token. DON'T SHARE WITH ANYONE.
bot-token: ""

# The ID of the Discord Server (Guild) to connect to.
guild-id: ""

# The ID of the Text Channel to write to and read messages to.
chat-ch-id: ""

# MESSAGE CUSTOMIZATION
# NOTE: {player} -> player name, {adv} -> advancement name
# {msg} -> message name
# & -> colour code operator (look up Bukkit colour codes for this)
# NOTE: For '&', formatting goes before colour. Won't work otherwise.
# This means that discord-msg needs to have the bold formatting code before
# some colour code, for e.g. &l&b works. &b&l won't.
# * * -> italicised; ** ** -> bold; *** *** -> mix of both
# look up Discord formatting for more!

# Message that will be sent from Discord to Minecraft
dc-chat-msg: "&l{player}:&r {msg}"

# Message that will be sent from Minecraft to Discord
mc-chat-msg: "**{player}:** {msg}"

# Following are for server start, stop and player join, quit, advancement messages
start-msg: "Server was **started**!✅"
stop-msg: "Server has been **stopped**.🛑"
join-msg: "📥***{player}*** *just joined the server!*"
quit-msg: "📤***{player}*** *has left the server.*"
adv-msg: "⛏️***{player}*** *has completed the advancement* ***{adv}*** *!*"

# Notification sound (in-game)
notif:
  sound: ENTITY_EXPERIENCE_ORB_PICKUP
  volume: 0.15
  pitch: 1.16

# Discord Chat Channel Topic
dc-topic: "{players_online} of {player_limit} players online"