name: DTMBridge
version: '1.0'
main: com.github.buoyy.dtm.DTMBridge
api-version: '1.21'
load: STARTUP
commands:
  dtminfo:
    description: Informs sender about plugin.
    usage: /<command>
  dtmlink:
    description: Sends a key to the player to be sent to the bot for account linking. 
    usage: /<command>
  dtmlinks:
    description: Sends a map of all accounts linked.
    usage: /<command>